// System architecture: layered components + the end-to-end data flow.
module.exports = {
  components: [
    { id: "frontend", name: "Frontend", tags: ["Svelte 5", "Electron"],
      role: "Operator interface: live POV, overlays, spatial 3D view, roster and analytics.",
      details: "A Svelte 5 (runes) app in an Electron desktop shell, or any modern browser against the backend. Renders the WebGL feed, detection / ghost / heatmap overlays, the tactical radar and the three.js spatial viewport." },
    { id: "backend", name: "Backend", tags: ["Python", "Threads"],
      role: "Orchestrates capture, analysis and persistence.",
      details: "A headless orchestrator wires camera → FrameBuffer → AnalysisWorker. Analysis runs on worker threads; results hop to the async event loop for fan-out. No Qt, the same core drives both desktop and web." },
    { id: "inference", name: "Inference Engine", tags: ["PyTorch", "CUDA"],
      role: "Runs the model catalogue with FP16 acceleration.",
      details: "A model manager selects device (CUDA / CPU) and loads vendored weights. Detection, depth, segmentation, pose, Re-ID and super-resolution share the runtime with bounded, interval-scheduled work." },
    { id: "model-pipeline", name: "Model Pipeline", tags: ["Plugins"],
      role: "Composes models into the 13-stage processing flow.",
      details: "A plugin manager registers detectors and analysers; the AnalysisWorker runs them per frame and assembles an AnalysisResult (detections dict, metrics, motion) consumed downstream." },
    { id: "storage", name: "Storage", tags: ["SQLite"],
      role: "Local persistence for sources, events, identities and settings.",
      details: "A thread-safe SQLite store holds sources, events, alerts, subjects / dossiers, zones and key-value settings. Snapshots and clips live on disk. Nothing leaves the host." },
    { id: "api", name: "API Layer", tags: ["FastAPI", "WebSocket"],
      role: "Streams live data and exposes REST endpoints.",
      details: "FastAPI serves REST (sources, roster, spatial, suggestions, detection filters, AI) and a WebSocket that streams frames, detections, metrics and alerts. Commands flow back over the same socket." },
    { id: "visualization", name: "Visualization Layer", tags: ["three.js", "WebGL"],
      role: "Renders overlays and the 3D reconstruction.",
      details: "three.js renders the point-cloud / mesh scene with a fly-through camera; a WebGL layer composites the live feed; SVG / canvas draw the HUD overlays, tactical radar and heatmaps." },
    { id: "export", name: "Export Layer", tags: ["Clips", "Scenes"],
      role: "Turns analysis into shareable artifacts.",
      details: "Incident clips, journey supercuts, reconstructed scenes, identity dossiers and event timelines are exported on demand; a background recorder captures continuous / motion / event footage." },
    { id: "data-flow", name: "Data Flow", tags: ["Event bus"],
      role: "How a frame becomes an event.",
      details: "StreamReader → FrameBuffer (drop-oldest) → AnalysisWorker (models) → AnalysisResult → EventBus fan-out to recording, alerting, the timeline, the API stream and the UI." },
  ],
  // Text-diagram of the request/data path, rendered in a <pre> on the page.
  flow: [
    "  Camera / RTSP / File / Image",
    "            |",
    "     StreamReader (thread)",
    "            v",
    "     FrameBuffer  (drop-oldest, bounded)",
    "            v",
    "   AnalysisWorker (thread)  ──►  Model Pipeline",
    "            |                    ├─ YOLO11 + ByteTrack   (detection / tracking)",
    "            |                    ├─ Depth Anything V2     (depth)",
    "            |                    ├─ Seg / Pose / Re-ID    (masks / gait / identity)",
    "            |                    └─ Geometry + SR         (3D / reconstruction)",
    "            v",
    "     AnalysisResult ──► EventBus ──┬─► Recorder (clips)",
    "            |                      ├─► Alert + Threat engine",
    "            |                      ├─► SQLite (events, subjects, settings)",
    "            v                      └─► FastAPI",
    "     WebSocket stream ─────────────────► Frontend (overlays + 3D viewport)",
  ],
};
