// Version history (newest first). Each release renders as an expandable entry.
module.exports = {
  releases: [
    { version: "0.12.12", codename: "Fourth Dimension", date: "2026-08-04", tag: "latest",
      changes: [
        { type: "fixed", text: "macOS \"'Overseer' is damaged and can't be opened\": the app is now code-signed (ad-hoc) with hardened-runtime entitlements, so once you clear the download quarantine with `xattr -cr /Applications/Overseer.app` it launches and runs the bundled Python properly (before, the missing entitlements could block it even after that). This is a Gatekeeper block on any un-notarized download, not a corrupt file; Windows and Linux are unaffected." },
        { type: "added", text: "The release pipeline is now notarization-ready: add an Apple Developer ID via repo secrets (MAC_CSC_LINK, MAC_CSC_KEY_PASSWORD, APPLE_ID, APPLE_APP_SPECIFIC_PASSWORD, APPLE_TEAM_ID) and tagged builds are signed and notarized automatically, so macOS opens them with no warning at all." },
      ] },
    { version: "0.12.11", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "improved", text: "Another step on video smoothness: the whole display path (the camera reader and the 30fps encoder) now runs at a raised OS thread priority, while the background analysis, roster-harvest and vehicle classifiers run at a lowered one. So under load the operating system hands the CPU to the live feed first. This complements the thread-pool caps from the previous release." },
      ] },
    { version: "0.12.10", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "fixed", text: "Live video stutter, attacked at the real root cause: in one process nothing capped the OpenCV and torch thread pools, so a single analysis op grabbed every CPU core and starved the 30fps display encoder in bursts. Both pools are now capped to cores-2, the display-encoder thread runs at a raised priority, and per-detection colour analysis is cached per track instead of recomputed every frame." },
        { type: "improved", text: "While you are watching one camera live, the background roster harvest of the OTHER cameras is now paused entirely (only the focused camera keeps enrolling), removing the periodic GPU/GIL spikes from their detection and re-ID. It resumes when you leave the feed." },
        { type: "changed", text: "The README now leads with the AI Operator (voice and text control) instead of the older assistant, with a real screenshot; the HoloReel clip spans the full width; and the Vehicle/Person profile and smart-suggestion descriptions were tightened." },
      ] },
    { version: "0.12.9", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "improved", text: "Social X-ray no longer competes with the video for the main thread: its per-frame overlay pass is throttled to about 30fps and an O(n^2) lookup was removed, so the feed stays smooth while it is on, especially with several people on screen." },
        { type: "fixed", text: "Social X-ray (and the pose-based facing / gait / hand-raise) used to appear only after a multi-second wait because the pose model was loaded lazily on the analysis worker the first time it ran, stalling the pipeline. The pose model is now warmed up off-thread when a camera connects, so cones and links show up promptly." },
        { type: "added", text: "HoloReel and Social X-ray now have a real demo clip and screenshot in the README and the gallery, and their descriptions were tightened." },
      ] },
    { version: "0.12.8", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "fixed", text: "HoloReel would sometimes freeze on a single frame (like a plain recapture) when the live capture ring was not advancing. It now falls back to reading a consecutive burst straight from the source, so the reel is always a real moving clip, and a CAPTURING indicator shows while it grabs the frames." },
        { type: "fixed", text: "The AI operator no longer answers 'could not read frame' for visual questions (e.g. a vehicle's brand): frame grab now prefers the live capture frame (always present) instead of the slower analysis frame that was often empty between passes." },
        { type: "fixed", text: "Person height estimate was pinned near 200 cm for almost everyone; recalibrated so a normally framed adult reads around 170 cm." },
        { type: "improved", text: "Live narration is far richer: instead of just a head count it describes subjects by clothing colour, height, intent (loitering / hurrying / waiting), who is facing the camera, groupings, and calls out people or vehicles entering and leaving. It varies each time and works with no vision model configured." },
        { type: "improved", text: "Speech-to-text upgraded to large-v3-turbo, a big accuracy jump for Turkish and English, at low VRAM." },
        { type: "added", text: "An ENHANCE button now sits at the bottom-left with the scene tools (it was keyboard-only), and 'Look closer' is renamed 'Scan point' so it no longer reads like a zoom control." },
      ] },
    { version: "0.12.7", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "fixed", text: "HoloReel looked frozen (a single 3D frame) even though the frames were distinct: all of them were grabbed in a tight loop and landed inside a sub-second window, so almost no motion happened across the reel. Capture and reconstruction are now interleaved, and a minimum per-frame stride spreads the frames across about three seconds of real time, so the replay actually flows. Confirmed by an offline timing harness: the reel window went from ~0.9s to ~3.3s of real motion." },
      ] },
    { version: "0.12.6", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "improved", text: "HoloReel now captures genuinely different consecutive frames: the backend waits for each new raw frame before grabbing the next, so a burst is a real short clip instead of the same moment repeated. Every frame is reconstructed and precomputed up front, then playback is just a visibility switch, so it flows like a video with no per-frame freeze while you fly through it." },
        { type: "improved", text: "Social X-ray connection labels are lighter and spaced further apart, so the text on the lines no longer reads as bold or overlaps." },
        { type: "added", text: "Social X-ray and HoloReel are now documented in the README and on the site." },
      ] },
    { version: "0.12.5", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "improved", text: "Video delivery decoupled further: the stream now runs in a worker thread instead of on the server event loop, and the background roster harvester (which runs detection on every camera) backs off about 8x while you are watching a camera live, freeing the GPU and interpreter. The display encoder was independently confirmed to hold 30fps even under heavy load." },
        { type: "improved", text: "HoloReel captures frames back to back at a lighter grid so they sit closer together in time, and playback advances only when a frame has finished rebuilding, so it no longer skips." },
        { type: "fixed", text: "Social X-ray interaction labels are back (a tightened facing test had removed almost all links); labels no longer stack on each other, and the facing judgement stays strict." },
      ] },
    { version: "0.12.4", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "fixed", text: "The actual video-smoothness bug: the display encoder ran sleep(1/30)+encode back to back, so it only hit ~22 fps and stuttered. It is now deadline-paced to a real 30 fps, with a 1ms timer and a shorter GIL switch interval so the encoder and the server loop share time cleanly. The feed should finally be smooth." },
        { type: "added", text: "HoloReel: capture a few seconds of successive 3D reconstructions, then replay them like a video with a scrub bar while you fly through the scene in 3D. Pause any time. (The 3D live mode keeps its old LIVE name.)" },
        { type: "improved", text: "Detection boxes glide more smoothly (more velocity feed-forward to carry them between updates)." },
        { type: "improved", text: "Social X-ray: link labels no longer overlap, and the facing test is stricter so a link is a definite judgement." },
      ] },
    { version: "0.12.3", codename: "Fourth Dimension", date: "2026-08-03", tag: "",
      changes: [
        { type: "improved", text: "Smooth video, properly this time. The real cause was the single server event loop being saturated by an unthrottled per-frame detections push plus a blocking status heartbeat, which starved the stream. The detections push is now throttled, the heartbeat runs off the loop (and the GPU handle is cached, not re-opened every 2s), and a dedicated encoder thread produces the display feed at a steady 30fps independent of analysis." },
        { type: "improved", text: "Social X-ray is much easier to read: links persist far longer (about 3 seconds) so you can follow them, the attention cone starts at eye level, and focusing a person (click) now shows only that person's cone and links, nothing else." },
        { type: "changed", text: "Chronoscape is replaced by Walkthrough: the 3D view keeps rebuilding from successive captures so you can move through the live scene in 3D, instead of replaying trails." },
      ] },
    { version: "0.12.2", codename: "Fourth Dimension", date: "2026-08-02", tag: "",
      changes: [
        { type: "improved", text: "Big analysis speed-up: the wind analyzer's dense optical flow (the single biggest per-frame cost) now runs on a downscaled frame, plus a cheaper sharpness metric and throttled background-plate / fallback encode. Roughly 5x the analysed frame rate, so a crossing car is tracked across many more frames." },
        { type: "improved", text: "Social X-ray is readable now: eased motion and hysteresis (links fade in and linger instead of flickering), only real interactions are drawn (no lines to unrelated distant people), shorter attention cones, and clicking a person shows only that person's interactions." },
        { type: "fixed", text: "Colour is more accurate for cars and people: it reads the central core (less background bleed), names the dominant colour cluster, and a dark reflective body is read as black instead of blue." },
        { type: "fixed", text: "Chronoscape is clearer: paths also draw on the top-down minimap (robust and legible), depth is sampled robustly so a marker no longer flies off into the distance." },
        { type: "fixed", text: "Occlusion x-ray defaults off and remembers being turned off." },
      ] },
    { version: "0.12.1", codename: "Fourth Dimension", date: "2026-08-02", tag: "",
      changes: [
        { type: "improved", text: "Much smoother live video: the displayed feed now runs at camera rate, decoupled from the (slower) analysis pipeline, with detection boxes interpolated on top. No loss of analysis quality." },
        { type: "fixed", text: "Chronoscape now works: it freezes a fixed clip of the recorded history on entry (no more markers drifting over the frozen scene), scopes trails to the camera, drops standing-still jitter, and says so when there is no movement to replay yet." },
        { type: "fixed", text: "Social X-ray is conservative: it only links people with real evidence (facing each other, watching, approaching). People merely standing side by side, like a queue, are no longer labelled as together." },
      ] },
    { version: "0.12.0", codename: "Fourth Dimension", date: "2026-08-02", tag: "",
      changes: [
        { type: "added", text: "Chronoscape: a 4D time-travel replay inside the 3D view. Every tracked subject's recent path is lifted onto the reconstructed ground as an age-graded trail, with playheads that glide along each path. Scrub or play the scene's last minutes through time." },
        { type: "added", text: "Social X-ray: each person's attention direction as a cone, and live links between people who are interacting (engaged, watching, together, approaching), from a pose-derived facing that works even when they stand still." },
        { type: "added", text: "Both are driven from the operator by voice or text (\"time travel\", \"social x-ray\") and the modules rail; S toggles Social X-ray, the CHRONO button opens time-travel." },
      ] },
    { version: "0.11.2", codename: "Acuity", date: "2026-08-02", tag: "",
      changes: [
        { type: "added", text: "Vehicle body type (sedan, hatchback, SUV, station wagon, pickup, van, minibus...) via zero-shot CLIP, shown on cards and filterable in the roster." },
        { type: "added", text: "Estimated person stature (band plus approximate cm), shown on the card and filterable." },
        { type: "added", text: "More read behaviours: sitting, lying, swimming, standing, approaching and moving away, from posture, motion and apparent size." },
        { type: "improved", text: "Clothing colour reads from the torso only and is shown only when it is clearly that colour, so a murky crop no longer gets a wrong one; a shirtless torso is reported as bare skin." },
        { type: "improved", text: "Live Enhance is sharper and more natural: multi-pass reconstruction fitted to the loupe, no cartoon or pixel blocks." },
        { type: "improved", text: "Turkish speech-to-text accuracy, on a larger on-device Whisper model." },
        { type: "fixed", text: "Voice and body type no longer fail on a full GPU (speech-to-text falls back to CPU, body type runs on CPU). Storage counts every snapshot and clip on disk. The operator answers on-screen visual questions by looking at the frame." },
      ] },
    { version: "0.10.0", codename: "AI Operator", date: "2026-08-02", tag: "",
      changes: [
        { type: "added", text: "AI Operator: run the whole app by voice or text, 70+ chained actions with data passing between steps, and vision Q&A about what is on screen." },
        { type: "added", text: "Offline voice: on-device Whisper speech-to-text (Turkish + English) and spoken replies." },
        { type: "added", text: "Live narration, follow-cam, and occlusion x-ray." },
        { type: "added", text: "Live 'enhance': box-select any region for a photographic close-up." },
        { type: "added", text: "Auto zone detection surfaced in Smart Suggestions — proposed, editable, and explained." },
        { type: "fixed", text: "Colour naming, vehicle attributes, storage stats, forensic precision and detection-box alignment." },
      ] },
    { version: "0.9.0", codename: "Spatial Foresight", date: "2026-07-31", tag: "",
      changes: [
        { type: "added", text: "Tactical god-view radar with depth-locked contact placement (Depth Anything)." },
        { type: "added", text: "Predictive ghosts overlay with path-convergence detection." },
        { type: "added", text: "Functional DETECTION class filters, gated at the detector and persisted." },
        { type: "changed", text: "Smart Suggestions redesigned as an interactive triage cockpit." },
      ] },
    { version: "0.8.0", codename: "Identity Intelligence", date: "2026-06-20", tag: "",
      changes: [
        { type: "added", text: "Cross-camera Re-ID with gait descriptors and soft biometrics." },
        { type: "added", text: "Long-term subject dossiers and relationship graph." },
        { type: "added", text: "Multi-frame + Real-ESRGAN super-resolution reconstruction." },
        { type: "fixed", text: "Reconstruction rejects mismatched crops to never do worse than zoom." },
      ] },
    { version: "0.7.0", codename: "Spatial Lift", date: "2026-05-05", tag: "",
      changes: [
        { type: "added", text: "3D reconstruction: point cloud + mesh with background completion." },
        { type: "added", text: "three.js spatial viewport with fly-through camera." },
        { type: "changed", text: "Depth pipeline moved to Depth Anything V2 with temporal fusion." },
      ] },
    { version: "0.6.0", codename: "Watchtower", date: "2026-03-18", tag: "",
      changes: [
        { type: "added", text: "Zones, alert rules and correlated threat scoring." },
        { type: "added", text: "Per-camera DNA / reputation and smart suggestions." },
        { type: "added", text: "ANPR, vehicle make (ViT) and ego-compensated speed." },
      ] },
    { version: "0.5.0", codename: "First Light", date: "2026-01-30", tag: "",
      changes: [
        { type: "added", text: "YOLO11 detection + ByteTrack tracking on live feeds." },
        { type: "added", text: "MOG2 motion, recording and the operator POV console." },
        { type: "added", text: "FastAPI bridge with WebSocket streaming and SQLite persistence." },
      ] },
  ],
};
