// Platform capabilities, grouped for the Features page and surfaced on the home page.
// Add a feature by dropping an object into the relevant group.
module.exports = {
  groups: [
    {
      title: "AI Operator",
      summary: "Run the whole system by voice or text — one command, chained across the app.",
      features: [
        { name: "Natural-language operator", status: "shipped", tags: ["Voice", "Text", "LLM"],
          blurb: "Speak or type a command and it is planned into a chain of system actions and executed.",
          detail: "An LLM planner turns any request into an ordered chain of 70+ actions with data passing between steps — go to a camera, find a subject, add it to the watchlist, enhance its photo, then report when it was last seen. It also answers questions from live data, and when a vision model is configured it looks at the frame to answer visual questions (\"what colour is that car\", \"what's in their hand\"). While it drives the app a border lights up and it steps aside into a companion dock." },
        { name: "Offline voice", status: "shipped", tags: ["Whisper", "TTS"],
          blurb: "On-device speech-to-text (Turkish + English) and spoken replies — no cloud.",
          detail: "faster-whisper transcribes locally (GPU-accelerated when present); replies are spoken through the OS voice. Push-to-talk with a live transcript and selectable input/output devices." },
        { name: "Live narration", status: "shipped", tags: ["VLM"],
          blurb: "The camera narrates itself aloud, as a subtitle — watch it or just listen.",
          detail: "With one key the vision model continuously describes the active camera; it falls back to a live-data narration when no vision model is set, so it is never silent." },
        { name: "Follow-cam", status: "shipped", tags: ["Digital PTZ"],
          blurb: "Lock a subject and the digital PTZ keeps them centred as they move.",
          detail: "Rides the same motion model as the boxes and re-acquires the target through brief losses; it drops out cleanly when the subject is truly gone." },
        { name: "Occlusion x-ray", status: "shipped", tags: ["Prediction"],
          blurb: "See where a tracked subject is even while they are behind cover.",
          detail: "Holds and extrapolates a subject along its last velocity when it passes behind an obstacle, drawn as a distinct predicted ghost." },
        { name: "Live enhance", status: "shipped", tags: ["Super-res"],
          blurb: "Draw a box on any region and get a crisp, photographic close-up.",
          detail: "The learned model reconstructs the region up to the loupe size in multiple passes and is then fitted down cleanly, so detail is genuinely rebuilt instead of block-upscaled, with edge-preserving denoise and gentle local contrast. A sharp optical zoom, not a cartoonish or pixelated upscale." },
      ],
    },
    {
      title: "Perception",
      summary: "Frame-level understanding: what is in view, where, and how it moves.",
      features: [
        { name: "Real-time object detection", status: "shipped", tags: ["YOLO11", "GPU"],
          blurb: "People, vehicles, animals and hazards detected on every analysed frame.",
          detail: "A YOLO11 backend runs on the live feed with a tuned per-class confidence floor (people get a lower floor for awkward poses). Class gating is applied at the detector, so disabling a class removes it from the entire downstream budget." },
        { name: "Semantic segmentation", status: "beta", tags: ["Masks"],
          blurb: "Per-pixel foreground / object masks for cleaner geometry and analytics.",
          detail: "Instance and foreground masks separate standing objects from the background plate, feeding scene completion and occlusion-aware reconstruction. Powered by a YOLO11-seg head." },
        { name: "Depth estimation", status: "shipped", tags: ["Depth Anything V2"],
          blurb: "Dense monocular depth from a single ordinary camera, no stereo rig.",
          detail: "Depth Anything V2 produces a relative inverse-depth field per frame, temporally fused across several frames (per-pixel median) to suppress monocular noise on the static scene." },
        { name: "Metric depth", status: "beta", tags: ["Scale"],
          blurb: "Depth lifted toward real-world units for distance and size readouts.",
          detail: "Normalised disparity is combined with camera FOV and ground-plane priors to approximate metric distance for speed, spacing and object-size estimates. Uncalibrated by default; calibration sharpens it." },
        { name: "Fine-grained attributes", status: "shipped", tags: ["CLIP", "Zero-shot"],
          blurb: "Vehicle body type, brand, colour; person clothing colour, stature and behaviour.",
          detail: "Zero-shot CLIP reads a vehicle's body type (sedan, hatchback, SUV, station wagon, pickup, van, minibus) and a gated ViT reads its brand; people get a perspective-normalised stature estimate and a posture-and-motion behaviour read (sitting, lying, swimming, walking, running, loitering). Clothing colour ignores bare skin so a shirtless subject is not labelled by skin tone. Every attribute is confidence-gated and searchable." },
        { name: "Object tracking", status: "shipped", tags: ["ByteTrack"],
          blurb: "Stable identities across frames, including brief occlusions.",
          detail: "ByteTrack assigns persistent track ids, and a coasting layer holds a last-known box briefly through momentary detection drops so tracklets do not flicker." },
        { name: "Multi-object tracking", status: "shipped", tags: ["MOT"],
          blurb: "Dozens of simultaneous tracklets with per-track motion state.",
          detail: "Each track carries velocity, dwell and trajectory history, feeding intent estimation, speed, the predictive-ghost overlay and the tactical god-view radar." },
        { name: "Camera pose estimation", status: "beta", tags: ["Ego-motion"],
          blurb: "Recovers camera motion so speeds are measured against the ground.",
          detail: "A per-frame optical-flow model fits the camera's ego-motion, so a dashcam or panning feed is compensated per object rather than reading everything as moving." },
        { name: "Camera calibration", status: "planned", tags: ["Intrinsics"],
          blurb: "Optional intrinsics + ground-plane calibration for metric accuracy.",
          detail: "A guided calibration flow (FOV, principal point, ground homography) upgrades metric depth, top-down projection and speed from plausible to measured." },
      ],
    },
    {
      title: "Spatial & 3D",
      summary: "Lifting flat 2D frames into navigable, structured 3D scenes.",
      features: [
        { name: "Scene understanding", status: "shipped", tags: ["Semantics"],
          blurb: "A structured read of the scene: entities, ground, background, hazards.",
          detail: "Detections, depth and masks are fused into a scene graph that separates movers from the static plate and tags each entity with class, depth and behaviour." },
        { name: "Spatial reasoning", status: "shipped", tags: ["Foresight"],
          blurb: "Reason about position, distance, convergence and near-future motion.",
          detail: "A foresight engine estimates ground-plane velocity per subject and predicts positions seconds ahead, flagging converging paths before they meet." },
        { name: "3D reconstruction", status: "shipped", tags: ["Point cloud"],
          blurb: "Turn a frame into a navigable 3D point cloud you can fly through.",
          detail: "The depth grid is back-projected through a pinhole model and rendered in three.js, with a completed background layer reconstructed behind foreground objects." },
        { name: "Point cloud generation", status: "shipped", tags: ["three.js"],
          blurb: "Coloured point clouds lifted from depth + RGB, per camera.",
          detail: "Each grid cell becomes a coloured point at its true depth; depth smoothing turns discontinuities into ramps and straddling triangles are culled for clean edges." },
        { name: "Mesh generation", status: "beta", tags: ["Surface"],
          blurb: "Triangulated surfaces from the depth field for solid scene geometry.",
          detail: "The point grid is triangulated into a continuous mesh with discontinuity-aware edge culling, producing a watertight-ish surface for the visible scene and its background layer." },
        { name: "Texture reconstruction", status: "beta", tags: ["Inpainting"],
          blurb: "Fills and textures the scene hidden behind people and vehicles.",
          detail: "A warmed background plate plus depth-and-texture inpainting reconstructs the wall, floor and scene occluded by movers, shipped as a second textured mesh layer." },
      ],
    },
    {
      title: "Analytics & Operations",
      summary: "From raw perception to alerts, identities and operator workflows.",
      features: [
        { name: "Live analytics", status: "shipped", tags: ["Metrics"],
          blurb: "Real-time counts, density, motion, speed and per-camera reputation.",
          detail: "A metrics stream carries counts, motion percentage, crowd density heatmaps and each camera's learned DNA, updated frame by frame over WebSocket." },
        { name: "Event detection", status: "shipped", tags: ["Rules", "Threat"],
          blurb: "Zones, rules and correlated threat scoring raise the right alerts.",
          detail: "A rule engine plus a correlation-based threat scorer fuse co-occurring events per camera, so dangerous combinations escalate even with no single rule configured." },
        { name: "Multi-camera support", status: "shipped", tags: ["Re-ID"],
          blurb: "Cross-camera re-identification, dossiers and relationship graphs.",
          detail: "Appearance embeddings, soft biometrics and gait descriptors re-identify subjects across cameras and time, building long-term dossiers and a who-was-with-whom graph." },
      ],
    },
    {
      title: "Input & Runtime",
      summary: "Where Overseer runs and what it ingests.",
      features: [
        { name: "Image processing", status: "shipped", tags: ["Single frame"],
          blurb: "Analyse a single still: detect, segment, depth, lift to 3D.",
          detail: "Any image can be pushed through the full pipeline for one-shot analysis, including on-demand super-resolution reconstruction of faces and plates." },
        { name: "Video processing", status: "shipped", tags: ["Offline"],
          blurb: "Batch-analyse recorded video into events, tracks and 3D scenes.",
          detail: "Recorded clips and looped sources run through the same pipeline as live feeds, producing an event timeline, tracklets and exportable scenes." },
        { name: "Edge inference", status: "beta", tags: ["Local"],
          blurb: "Runs on a single local workstation, no cloud round-trips.",
          detail: "All inference happens on the host. Model tiers (nano to large) trade latency for accuracy so the platform scales from a laptop GPU to a workstation." },
        { name: "GPU acceleration", status: "shipped", tags: ["CUDA", "FP16"],
          blurb: "CUDA + FP16 inference across detection, depth and super-resolution.",
          detail: "Detection, depth and Real-ESRGAN run half-precision on CUDA when available, with graceful CPU fallback for machines without a GPU." },
        { name: "Offline processing", status: "shipped", tags: ["Private"],
          blurb: "Fully air-gapped: no external calls, all data stays on the host.",
          detail: "Models are vendored and cached locally; the platform runs with no internet connection, and all footage, embeddings and events stay in a local SQLite store." },
      ],
    },
  ],
};
