// AI model catalogue. Each entry becomes a full model page (src/models/model.njk paginates
// over this list). Add a model = add an object here. Benchmarks are illustrative placeholders.
module.exports = [
  {
    slug: "yolo11", name: "YOLO11", role: "Object Detection", status: "shipped",
    tags: ["Detection", "CUDA", "FP16"],
    purpose: "Locate and classify people, vehicles, animals and hazards on every analysed frame.",
    description:
      "YOLO11 (Ultralytics) is the primary detector. Overseer runs it with per-class confidence floors, people get a lower floor to recover awkward poses, and applies class gating at the detector so disabling a class removes it from the entire downstream budget. Optional tiled (SAHI-style) inference recovers small, distant objects.",
    inputs: ["RGB frame (BGR ndarray)", "Target class set", "Confidence floor", "Image size (imgsz)"],
    outputs: ["Bounding boxes (xyxy)", "Class label + confidence", "Track id (with tracker)"],
    performance: "Real-time on a modern GPU at imgsz 1280. The nano tier suits laptops; the small tier is the live default; larger tiers trade latency for recall.",
    advantages: ["Fast and well-supported", "Strong small-object recall with tiling", "Per-class gating sheds load", "Stable across lighting via low-light pre-enhancement"],
    limitations: ["COCO-limited vocabulary (no open-vocabulary)", "Dedicated firearms need a specialist model", "Very small / heavily occluded objects still hard"],
    latency: "~8–16 ms / frame (yolo11s, imgsz 1280, FP16, RTX-class GPU)",
    hardware: "NVIDIA GPU recommended (CUDA); CPU fallback supported at reduced FPS",
    memory: "~1.5–3 GB VRAM (tier dependent)",
    exampleOutputs: ["4 persons + 6 vehicles on a street scene", "Per-box class, confidence and stable track id", "Tiled pass recovering distant pedestrians"],
    config: [
      { key: "detectors.yolo.model", value: "yolo11s.pt" },
      { key: "detectors.yolo.imgsz", value: "1280" },
      { key: "detectors.yolo.confidence", value: "0.25" },
      { key: "detectors.yolo.person_confidence", value: "0.18" },
      { key: "detectors.yolo.frame_interval", value: "2" },
    ],
    benchmarks: [
      { name: "COCO mAP50-95", dataset: "COCO val", metric: "mAP", value: "~47 (s tier)", hardware: "reference" },
      { name: "Live latency", dataset: "1280px feed", metric: "ms/frame", value: "~11", hardware: "RTX 3060" },
    ],
  },
  {
    slug: "bytetrack", name: "ByteTrack", role: "Multi-Object Tracking", status: "shipped",
    tags: ["Tracking", "MOT"],
    purpose: "Assign persistent identities to detections across frames, surviving brief occlusions.",
    description:
      "ByteTrack associates both high- and low-confidence boxes to keep tracks alive through partial occlusion. Overseer layers a short coasting window on top: a last-known box is held briefly through a momentary detection drop so tracklets do not flicker. Track ids key everything downstream, Re-ID, speed, intent, ghosts and the tactical radar.",
    inputs: ["Per-frame detections", "Previous track state"],
    outputs: ["Stable track id per object", "Track age / velocity state"],
    performance: "Negligible overhead relative to detection; runs inline on the detector output.",
    advantages: ["Robust through occlusion", "Cheap (association only)", "Foundation for all identity features"],
    limitations: ["Identity switches possible in dense crowds", "Long full occlusions break continuity", "2D only, no depth-aware association yet"],
    latency: "< 2 ms / frame",
    hardware: "CPU-bound; no GPU required",
    memory: "Negligible",
    exampleOutputs: ["Consistent ids as subjects cross the frame", "A tracklet coasting through a 2-frame detection gap"],
    config: [
      { key: "detectors.yolo.tracker", value: "bytetrack" },
      { key: "tracking.coast_frames", value: "3" },
    ],
    benchmarks: [
      { name: "MOTA", dataset: "MOT17 (ref)", metric: "MOTA", value: "~80", hardware: "reference" },
      { name: "Overhead", dataset: "live", metric: "ms/frame", value: "< 2", hardware: "CPU" },
    ],
  },
  {
    slug: "depth-anything-v2", name: "Depth Anything V2", role: "Monocular Depth", status: "shipped",
    tags: ["Depth", "Spatial", "CUDA"],
    purpose: "Estimate a dense depth field from a single ordinary camera, with no stereo rig.",
    description:
      "Depth Anything V2 predicts relative inverse-depth (disparity) per frame, larger = nearer. Overseer normalises it to [0,1], temporally median-fuses several frames to suppress monocular noise on the static scene, and back-projects it through a pinhole model to lift the frame into 3D. The depth field also drives the depth-locked tactical radar.",
    inputs: ["RGB frame", "Working resolution", "Fusion frame count"],
    outputs: ["Normalised disparity grid (float32)", "Point cloud (with RGB)", "Ground / background depth"],
    performance: "Runs on demand for the spatial view and periodically for the tactical radar; the Large tier gives the cleanest geometry.",
    advantages: ["No calibration or stereo needed", "Clean, temporally stable geometry", "Great zero-shot generalisation across scenes"],
    limitations: ["Relative, not metric, without calibration", "Reflective / transparent surfaces are hard", "Heavier than detection, run periodically, not every frame"],
    latency: "~120–400 ms / frame (Large tier, GPU); cached for the static scene",
    hardware: "NVIDIA GPU strongly recommended",
    memory: "~2–4 GB VRAM (tier dependent)",
    exampleOutputs: ["A coloured 3D point cloud of a street", "A ground-plane depth field behind occluding objects", "Depth-locked contact placement on the radar"],
    config: [
      { key: "spatial.enabled", value: "true" },
      { key: "spatial.input_width", value: "640" },
      { key: "spatial.fuse_frames", value: "3" },
      { key: "spatial.fov_deg", value: "60" },
    ],
    benchmarks: [
      { name: "δ<1.25", dataset: "NYU (ref)", metric: "accuracy", value: "~0.98", hardware: "reference" },
      { name: "Scene depth", dataset: "640px", metric: "ms", value: "~240", hardware: "RTX 3060" },
    ],
  },
  {
    slug: "real-esrgan", name: "Real-ESRGAN", role: "Super-Resolution", status: "shipped",
    tags: ["Reconstruction", "4x", "CUDA"],
    purpose: "Reconstruct a sharper, super-resolved image of a face or licence plate from many sightings.",
    description:
      "A vendored SRVGGNetCompact (realesr-general-x4v3) provides a 4x learned upscaler. Overseer caps and ECC-aligns a subject's crops, median-fuses them at low resolution to remove per-frame noise, then runs a single super-resolution pass so a blurry face or plate becomes legible. Weights load with no basicsr / gfpgan dependency.",
    inputs: ["Aligned, fused low-res crop (BGR)", "Max side hint"],
    outputs: ["4x upscaled BGR image", "Reconstruction metadata (frames used / offered)"],
    performance: "Sub-second per reconstruction thanks to the low-res-fuse, hi-res-finish strategy.",
    advantages: ["Legible faces / plates from blur", "No dependency hell (vendored net)", "Fuses multiple frames for real detail, not hallucination"],
    limitations: ["Cannot invent detail absent from all frames", "Mismatched crops are rejected to avoid worse-than-zoom output", "GPU strongly preferred for interactive latency"],
    latency: "~0.3 s / reconstruction (GPU)",
    hardware: "NVIDIA GPU recommended; CPU fallback works but is slow",
    memory: "~1 GB VRAM; ~5 MB model download",
    exampleOutputs: ["A readable bus destination sign from a blurry crop", "A clarified face from 12 sightings", "Original vs super-res comparison in the viewer"],
    config: [
      { key: "reconstruct.super_resolution", value: "true" },
      { key: "reconstruct.min_frames", value: "2" },
      { key: "reconstruct.max_frames", value: "16" },
      { key: "reconstruct.min_corr", value: "0.72" },
    ],
    benchmarks: [
      { name: "Upscale factor", dataset: "internal", metric: "x", value: "4", hardware: "-" },
      { name: "Reconstruct", dataset: "16 crops", metric: "s", value: "~0.3", hardware: "RTX 3060" },
    ],
  },
  {
    slug: "yolo11-seg", name: "YOLO11-seg", role: "Segmentation", status: "beta",
    tags: ["Masks", "Foreground"],
    purpose: "Produce per-pixel masks that separate standing objects from the background plate.",
    description:
      "A YOLO11 segmentation head yields instance / foreground masks. Overseer combines them with a depth-derived foreground mask to decide which pixels are 'standing objects', so scene completion can inpaint depth and texture behind them and reconstruct the occluded background as a real surface.",
    inputs: ["RGB frame"],
    outputs: ["Instance masks", "Foreground / standing-object mask"],
    performance: "Comparable to detection; used mainly for the spatial completion path rather than every live frame.",
    advantages: ["Clean mover / background separation", "Improves reconstruction seams", "Shares the YOLO backbone"],
    limitations: ["Mask edges soften on motion blur", "Thin structures under-segmented", "Beta: not yet wired into every analytic"],
    latency: "~12–20 ms / frame (GPU)",
    hardware: "NVIDIA GPU recommended",
    memory: "~2 GB VRAM",
    exampleOutputs: ["A person mask lifted off the wall behind them", "A foreground mask driving background inpainting"],
    config: [
      { key: "spatial.complete", value: "true" },
      { key: "detectors.seg.model", value: "yolo11n-seg.pt" },
    ],
    benchmarks: [
      { name: "Mask mAP", dataset: "COCO (ref)", metric: "mAP", value: "~40", hardware: "reference" },
    ],
  },
  {
    slug: "pose", name: "Pose Estimator", role: "Body Keypoints", status: "beta",
    tags: ["Keypoints", "Gait"],
    purpose: "Extract body keypoints to support intent, posture cues and gait sampling.",
    description:
      "A keypoint model runs periodically (every few frames) on tracked people. The skeletons feed behavioural intent estimation, posture / fall cues, and the gait descriptor that contributes to cross-camera re-identification. Running it on an interval keeps it off the per-frame critical path.",
    inputs: ["Person crop / frame", "Track id"],
    outputs: ["2D keypoints per person", "Gait descriptor contribution"],
    performance: "Interval-scheduled (e.g. every 5th frame) so it adds bounded cost to the pipeline.",
    advantages: ["Enables intent + gait", "Interval scheduling caps cost", "Robust to partial visibility"],
    limitations: ["Crowded overlap confuses keypoints", "Needs enough resolution on the subject", "Beta accuracy on unusual poses"],
    latency: "~5–12 ms / person (GPU)",
    hardware: "NVIDIA GPU recommended",
    memory: "~1–2 GB VRAM",
    exampleOutputs: ["A walking skeleton feeding a gait signature", "Posture cues for intent estimation"],
    config: [
      { key: "pose.enabled", value: "true" },
      { key: "pose.interval", value: "5" },
    ],
    benchmarks: [
      { name: "Keypoint AP", dataset: "COCO (ref)", metric: "AP", value: "~68", hardware: "reference" },
    ],
  },
  {
    slug: "reid-gait", name: "ReID + Gait", role: "Re-identification", status: "shipped",
    tags: ["Identity", "Embeddings"],
    purpose: "Re-identify subjects across cameras and time to build long-term dossiers.",
    description:
      "Appearance embeddings, soft biometrics (colour, height, accessories) and z-scored, winsorized gait descriptors are fused into a subject signature. Cosine matching links sightings across cameras and days, powering repeat-visitor detection, movement trails, relationship graphs and the identity dossier.",
    inputs: ["Person crop", "Track id", "Gait sequence"],
    outputs: ["Appearance embedding", "Subject uid + match score", "Soft-biometric attributes"],
    performance: "Embedding is per-sighting; matching is a cosine lookup against the subject store.",
    advantages: ["Cross-camera + cross-day identity", "Gait adds a hard-to-spoof cue", "Feeds dossiers and relationship graphs"],
    limitations: ["Appearance drifts with clothing / lighting", "Gait needs a clean walking sequence", "Probabilistic, surfaced with confidence, not certainty"],
    latency: "~10–25 ms / embedding (GPU)",
    hardware: "NVIDIA GPU recommended; embeddings serialised to avoid contention",
    memory: "~1 GB VRAM",
    exampleOutputs: ["A repeat visitor flagged across three cameras", "A long-term dossier with sighting histogram", "A who-was-with-whom relationship graph"],
    config: [
      { key: "roster.persist", value: "true" },
      { key: "roster.persist_threshold", value: "0.74" },
      { key: "gait.enabled", value: "true" },
    ],
    benchmarks: [
      { name: "Rank-1", dataset: "internal", metric: "accuracy", value: "placeholder", hardware: "-" },
    ],
  },
  {
    slug: "vehicle-vit", name: "ViT Vehicle Classifier", role: "Vehicle Attributes", status: "beta",
    tags: ["Vehicles", "ANPR"],
    purpose: "Estimate vehicle make and support plate / speed attributes for tracked vehicles.",
    description:
      "A vision transformer estimates vehicle make from tracked-vehicle crops, confidence-gated and voted across frames to stay stable. It runs alongside licence-plate estimation (ANPR) and an ego-motion-compensated speed estimate, so each vehicle carries subtype, make, plate and a rough km/h read.",
    inputs: ["Vehicle crop", "Track id", "Frames for voting"],
    outputs: ["Estimated make (confidence-gated)", "Plate string (ANPR)", "Speed estimate (km/h)"],
    performance: "Runs on an interval per tracked vehicle, off the critical path, voted over time.",
    advantages: ["Adds rich vehicle attributes", "Voting stabilises noisy single-frame reads", "Complements plate + speed"],
    limitations: ["Make limited to trained classes", "Plates need adequate resolution / angle", "Speed uncalibrated, comparable, not exact"],
    latency: "~8–15 ms / crop (GPU)",
    hardware: "NVIDIA GPU recommended",
    memory: "~1–2 GB VRAM",
    exampleOutputs: ["A tracked car labelled with make + plate + km/h", "A voted make that stabilises over several frames"],
    config: [
      { key: "vehicle.make.live_interval", value: "4.0" },
      { key: "vehicle.anpr.enabled", value: "true" },
    ],
    benchmarks: [
      { name: "Make top-1", dataset: "internal", metric: "accuracy", value: "placeholder", hardware: "-" },
    ],
  },
];
