// The processing pipeline, stage by stage. Each stage renders as an expandable panel on the
// Pipeline page and as a node on the home-page ribbon.
module.exports = {
  stages: [
    { no: "01", name: "Input", purpose: "Acquire a source: live camera, RTSP/ONVIF stream, recorded video or a single image.",
      details: "A source is registered (RTSP/ONVIF discovery, a file, or a looped clip). The reader opens the stream on its own thread and hands frames to a drop-oldest buffer so the analysis stage never blocks the camera.",
      inputs: ["Camera / stream URL", "Video file", "Still image"], outputs: ["Raw frames"], tech: ["StreamReader", "ONVIF"] },
    { no: "02", name: "Frame Capture", purpose: "Pull frames into a bounded buffer with backpressure.",
      details: "Frames land in a fixed-size FrameBuffer (drop-oldest). A health monitor watches for freezes and reconnects. A rolling window of recent frames is retained for incident clips and appearance search.",
      inputs: ["Raw frames"], outputs: ["Buffered frames", "Clip ring"], tech: ["FrameBuffer", "HealthMonitor"] },
    { no: "03", name: "Preprocessing", purpose: "Normalise, low-light enhance and resize before inference.",
      details: "Dark frames are auto-enhanced so faint subjects are still found; frames are resized to the working resolution. A background plate (EMA) accumulates the true static scene for later completion.",
      inputs: ["Buffered frame"], outputs: ["Working frame", "Background plate"], tech: ["Low-light enhance", "EMA plate"] },
    { no: "04", name: "Detection", purpose: "Detect and classify objects with YOLO11 + class gating.",
      details: "YOLO11 runs with per-class confidence floors and optional tiling. Disabled classes are dropped at the detector so nothing downstream pays for them. ByteTrack assigns stable ids inline.",
      inputs: ["Working frame", "Enabled classes"], outputs: ["Boxes + labels + track ids"], tech: ["YOLO11", "ByteTrack"] },
    { no: "05", name: "Segmentation", purpose: "Mask standing objects vs the static background plate.",
      details: "Instance / foreground masks (YOLO11-seg) combine with a depth-derived foreground mask to decide which pixels are movers, so the background behind them can be reconstructed.",
      inputs: ["Working frame", "Depth"], outputs: ["Foreground masks"], tech: ["YOLO11-seg"] },
    { no: "06", name: "Depth Estimation", purpose: "Estimate a dense monocular depth field.",
      details: "Depth Anything V2 produces relative inverse-depth, temporally median-fused across frames to suppress noise. The result is normalised to [0,1] and forms the geometry backbone.",
      inputs: ["Working frame"], outputs: ["Normalised disparity grid"], tech: ["Depth Anything V2"] },
    { no: "07", name: "Pose Estimation", purpose: "Extract body keypoints for intent and gait.",
      details: "A keypoint model runs on an interval over tracked people. Skeletons feed intent, posture cues and the gait descriptor used for cross-camera re-identification.",
      inputs: ["Person crops"], outputs: ["Keypoints", "Gait samples"], tech: ["Pose model"] },
    { no: "08", name: "Geometry Fusion", purpose: "Fuse depth, masks and detections into scene geometry.",
      details: "Depth is ground-plane fitted behind occluders; foreground masks and boxes mark movers; a completed background depth + texture is inpainted so the scene continues behind objects.",
      inputs: ["Depth", "Masks", "Background plate"], outputs: ["Scene + background geometry"], tech: ["Plane fit", "TELEA inpaint"] },
    { no: "09", name: "3D Reconstruction", purpose: "Back-project depth into a coloured point cloud.",
      details: "The depth grid is unprojected through a pinhole model into a coloured point cloud, with depth smoothing so surfaces stay continuous and discontinuities are ramped rather than torn.",
      inputs: ["Fused geometry", "RGB grid"], outputs: ["Point cloud"], tech: ["Pinhole", "three.js"] },
    { no: "10", name: "Mesh Optimization", purpose: "Triangulate and clean the surface.",
      details: "The point grid is triangulated into a mesh; triangles straddling a depth discontinuity (object silhouettes) are culled, yielding clean edges for both the scene and the background layer.",
      inputs: ["Point cloud"], outputs: ["Optimised mesh"], tech: ["Triangulation", "Edge culling"] },
    { no: "11", name: "Texture Mapping", purpose: "Project RGB (and inpainted texture) onto the mesh.",
      details: "The framed RGB, plus the inpainted background texture behind movers, is mapped onto the mesh, so occluded walls and floor render as real, textured surfaces.",
      inputs: ["Mesh", "RGB + inpainted texture"], outputs: ["Textured scene"], tech: ["UV projection"] },
    { no: "12", name: "Spatial Analysis", purpose: "Reason over the scene: tracks, foresight, identity, alerts.",
      details: "Tracks gain velocity and predicted positions (foresight); contacts are placed on the depth-locked tactical radar; Re-ID links identities; the rule + threat engine raises correlated alerts.",
      inputs: ["Tracks", "Depth", "Embeddings"], outputs: ["Predictions", "Identities", "Alerts"], tech: ["Foresight", "Re-ID", "Threat scorer"] },
    { no: "13", name: "Output", purpose: "Stream results and export scenes, clips and events.",
      details: "Frames, detections, metrics and alerts stream over WebSocket to the UI. Scenes, incident clips, dossiers and event timelines can be exported. Everything persists locally in SQLite.",
      inputs: ["All stage results"], outputs: ["Live streams", "Exports", "Event store"], tech: ["FastAPI", "WebSocket", "SQLite"] },
  ],
};
